# Tensor

In this notebook, we introduce the concept of PyTorch's `Tensor`.

We will also discuss the basic operations starting from creating a tensor to calculate gradients of tensor with AutoGrad Engine.

In [1]:
import torch

x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


The term `Tensor` has different meanings in different contexts.

In mathematics, a tensor is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space.

In physics, a tensor is a quantity that transforms according to certain rules under a change of coordinate system.

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`). You can see them as generalizations of vectors and matrices to higher dimensions.

- Scalar: Tensor of rank 0, a single number.
- Vector: Tensor of rank 1, an array of numbers.
- Matrix: Tensor of rank 2, an array of vectors.
- Triad ...

## Create a Tensor

PyTorch has provide many factory functions to create a tensor:

See more at: https://pytorch.org/docs/stable/torch.html#creation-ops

In [2]:
zeros = torch.zeros(3, 4)
print(zeros)

ones = torch.ones(3, 4)
print(ones)

torch.manual_seed(1016)
random = torch.rand(3, 4)
print(random)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.6908, 0.3720, 0.0406, 0.6789],
        [0.3997, 0.6253, 0.9242, 0.2651],
        [0.3892, 0.0518, 0.0906, 0.9304]])


In [3]:
x = torch.empty(3, 4, device="mps", dtype=torch.half)
print(x.shape)
print(x)

rand_like_x = torch.randn_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='mps:0', dtype=torch.float16)
torch.Size([3, 4])
tensor([[ 0.6665,  0.7134,  0.6162, -0.5879],
        [-0.5425, -1.5439,  0.0021, -0.8130],
        [ 0.7578,  2.0605, -0.2642, -1.1396]], device='mps:0',
       dtype=torch.float16)


## Important Properties of a Tensor

Basic:

- `dtype`: The data type of the tensor.
- `ndim`: The number of dimensions of the tensor.
- `shape`: The size of each dimension of the tensor.
- `device`: The device where the tensor is stored (CPU, CUDA or XLA).
- `layout`: The memory layout of the tensor (dense or sparse COO).

Gradient:

- `requires_grad`: Whether the tensor requires gradient.
- `grad`: The gradient of the tensor.
- `grad_fn`: The function that generated the tensor.
- `is_leaf`: Whether the tensor is a leaf in the computation graph.

<!-- Internal Storage:

- `storage()`: The storage of the tensor.
- `data_ptr()`: The address of the first element in the tensor.
- `stride()`: The number of elements in the storage that have to be skipped over to obtain the elements of a tensor. -->

### Basic

In [4]:
a = torch.ones((3, 4), dtype=torch.int16)
print(a)

b = torch.rand_like(a, dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)
tensor([[13.0198, 16.0610,  4.7514,  5.9108],
        [ 3.1010, 15.6271, 11.1551, 10.0684],
        [18.2956, 19.2786,  8.5177,  0.6904]], dtype=torch.float64)
tensor([[13, 16,  4,  5],
        [ 3, 15, 11, 10],
        [18, 19,  8,  0]], dtype=torch.int32)


In [5]:
a = torch.randn((3, 4))
print(a)

b = torch.randn((3, 4))
print(b)

c = a + b
print(c)

d = a @ b.T
print(d)

tensor([[ 0.6603, -0.4663,  0.0734,  1.6570],
        [-0.6467,  0.9516, -1.3104, -0.3421],
        [ 0.7025, -0.1641,  0.8990, -0.0474]])
tensor([[-0.6397,  1.0382,  0.0667, -2.1791],
        [ 0.8976,  0.3757,  0.1191,  1.6991],
        [ 0.8824,  1.0559, -1.8508,  0.4140]])
tensor([[ 0.0206,  0.5719,  0.1401, -0.5221],
        [ 0.2508,  1.3274, -1.1913,  1.3570],
        [ 1.5849,  0.8918, -0.9517,  0.3666]])
tensor([[-4.5125,  3.2416,  0.6404],
        [ 2.0599, -0.9603,  2.7179],
        [-0.4566,  0.5955, -1.2370]])


### Operations

In [6]:
a = torch.ones((3, 4))
print(a)

b = a.view(4, 3)
print(b)

c = b.view(2, 6)
print(c)

d = c.flatten()
print(d)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [7]:
a = torch.rand(3, 4)
print(a)

b = torch.randn(3, 4)
print(b)

c = a @ b.T
c *= 2
print(c)

d = a + b
d += 1
print(d)

tensor([[0.1379, 0.1332, 0.8050, 0.1002],
        [0.7714, 0.4699, 0.8556, 0.0173],
        [0.1460, 0.2148, 0.9696, 0.7340]])
tensor([[ 0.5502, -0.4122, -2.0075, -0.4726],
        [ 0.9428, -0.1016,  0.2102,  1.4780],
        [ 1.0216, -0.1620, -0.5636, -0.1097]])
tensor([[-3.2850,  0.8675, -0.6908],
        [-2.9902,  1.7699,  0.4557],
        [-4.6030,  2.8092, -1.0251]])
tensor([[ 1.6880,  0.7210, -0.2025,  0.6277],
        [ 2.7142,  1.3682,  2.0658,  2.4953],
        [ 2.1677,  1.0528,  1.4060,  1.6244]])


### Gradients

In [8]:
x = torch.randn(3, 4, requires_grad=True)
y = torch.randn(3, 4, requires_grad=True)

v = x * y
v.retain_grad()

w = v.log()
w.retain_grad()
w.sum().backward()

print(w)
print(w.grad)
print(v)
print(v.grad)

print(x)
print(x.grad)
print(y)
print(y.grad)

tensor([[-0.8888,     nan,     nan, -0.7540],
        [-1.4520, -0.6535,     nan, -1.6488],
        [ 0.5249, -0.3976, -0.4797,     nan]], grad_fn=<LogBackward0>)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[ 0.4112, -1.1335, -0.0548,  0.4705],
        [ 0.2341,  0.5202, -0.3102,  0.1923],
        [ 1.6903,  0.6719,  0.6189, -0.8087]], grad_fn=<MulBackward0>)
tensor([[  2.4321,  -0.8822, -18.2436,   2.1256],
        [  4.2718,   1.9223,  -3.2240,   5.2006],
        [  0.5916,   1.4883,   1.6156,  -1.2366]])
tensor([[ 0.6142, -1.0513,  0.0445,  1.2229],
        [-1.2099,  0.6368,  0.5492, -1.3099],
        [-1.2149,  1.1593, -1.0119, -1.0712]], requires_grad=True)
tensor([[ 1.6280, -0.9512, 22.4809,  0.8177],
        [-0.8265,  1.5704,  1.8207, -0.7634],
        [-0.8231,  0.8626, -0.9883, -0.9336]])
tensor([[ 0.6694,  1.0783, -1.2323,  0.3847],
        [-0.1935,  0.8169, -0.5647, -0.1468],
        [-1.3913,  0.5796, -0.6117,  0.7549]], require